### ISSUE TITLE
Animator Override animation references messed up on re-import/re-apply

### ISSUE THREAD

**Issue by aschearer** [Seanba/Aseprite2Unity#8]
Any time I reimport or change settings and apply them my animator's animation references are messed up. They appear good but don't play in game. Re-linking the animations fixes the issue. I suspect this may be due to the fact that the animations are created anew each time? Happy to dig further but could use a pointer.

**Comment by Seanba** [comment]
Hi there, @aschearer. I think I'm seeing that error too. Are you saying that you have to reset the `Motion` filed on an `Animator` state each time the sprite is re-imported?

I'll take a look but bear with me as I get spun up. It's been a while since I looked at this project. I figured an automatic importer for Aseprite files would be much more useful or popular but it doesn't get many downloads.

**Comment by Seanba** [comment]
Hi again, @aschearer. Can you tell me which version of Unity you are using?

**Comment by Seanba** [comment]
Sorry for all the messages, @aschearer, but can you try something?
Instead of re-linking all the animation clips after making a change to your aseprite can you try closing and restarting Unity?
In my case that "fixes" things for me.
I'm not saying that will be the _proper solution_ to this but it may be a clue of what I can do to provide a more robust fix.

**Comment by aschearer** [comment]
> Are you saying that you have to reset the Motion filed on an Animator state each time the sprite is re-imported?
Almost, I'm using an animation override controller, but yes I have to re-assign the overrides:
![image](https://user-images.githubusercontent.com/24077/154862986-8090516c-ce5a-4471-9e00-8280bdefb44c.png)

Unity version: 2020.3.25f1
Restarting: ... fixes the issue 🎉 def less severe now.

**Comment by Seanba** [comment]
Thanks, @aschearer. This appears to be a Unity bug where animation clips created by a custom importer are not properly re-serialized when the asset is re-imported. Version 1.1.3 contains a fix for this by forceing the re-serialization to happen at the right time.

Let me know if this works for you. Thanks.
https://seanba.itch.io/aseprite2unity/devlog/349634/aseprite-version-113

**Comment by aschearer** [comment]
Yes, that seems to fix it! You're amazing 🙌

**Comment by Seanba** [comment]
Right on. Thanks, and good luck with your game.
